### ISSUE TITLE
اجرا برنامه

### ISSUE THREAD

**Issue by nimamoradi** [SharifAIChallenge/AIC19-Server#6]
من نمی تونم برنامه سرور رو اجرا کنم
و این ارور رو میده 
<pre>java -jar server.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: ir/sharif/aichallenge/server/thefinalbattle/controller/GameEngine : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
</pre>

اگه با ide  اجرا کنم بعد 
هیچ کار نمی کنه کدش و فقط وصل می شه و بعد هیچ کدوم از متد های کد رو اجرا نمی کنه 

<pre>Info (ClientHandler): message receiving failure
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:154)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at ir.sharif.aichallenge.server.common.network.JsonSocket.get(JsonSocket.java:149)
	at ir.sharif.aichallenge.server.engine.network.ClientHandler.receive(ClientHandler.java:263)
	at ir.sharif.aichallenge.server.engine.network.ClientHandler.lambda$getReceiver$1(ClientHandler.java:225)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Info (JsonSocket): Message received: {"name":"token","args":["00000000000000000000000000000000"]}
Info (ClientNetwork): Client accepted.</pre>

**Comment by nimamoradi** [comment]
@RuhollahSeka کد درست شد
مگه token نباید شمراه منحصر به فرد هر بازی کن باشه ؟

**Comment by nimamoradi** [comment]
بعد این که اخرش برنده رو نشون نمی ده

**Comment by hamidreza004** [comment]
Jre تون چه ورژنیه؟

**Comment by nimamoradi** [comment]
ورژن 7 بود با 8 زدم اجرا شد
